spring:
  application:
    name: report-ms
  profiles:
    # Profile to import of config server
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"

server:
  port: 0
  servlet:
    context-path: /report-ms

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/