spring:
  application:
    name: companies-crud
  profiles:
    # Profile to import of config server
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    hikari:
      connection-timeout: ${spring.datasource.hikari.connection-timeout}
      maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: Trace

server:
  port: 8082
  servlet:
    context-path: /companies-crud

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /v3/api/api-docs
scalar:
  enabled: true
