spring:
  application:
    name: companies-crud
  datasource:
    url: jdbc:postgresql://172.17.249.96:5432/companies
    username: eduardo
    password: eduardo
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: Trace

server:
  port: 0
  servlet:
    context-path: /companies-crud

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /v3/api/api-docs
scalar:
  enabled: true
